name: deploy_docs
on:
  push:
    branches:
      - master 
      - main
      - native-system-setup-instructions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: git fetch
      - run: git config --global user.name "GitHub Action"
      - run: git config --global user.email "action@github.com"
      - run: pip install mkdocs-material mike
      - run: mike deploy ${GITHUB_REF##*/} --push